---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk

inputs:
- name: initializr-service
- name: version

outputs:
- name: release

run:
  path: initializr-service/ci/scripts/build-no-test.sh